### ISSUE TITLE
Доступ к коду

### ISSUE THREAD

**Issue by ValentinKarev** [rulonchik/rulonchik.github.io#1]
Здравствуйте, подскажите как получить доступ к коду данного проекта?

**Comment by ValentinKarev** [comment]
К проекту по синтезу речи

**Comment by rulonchik** [comment]
> Здравствуйте, подскажите как получить доступ к коду данного проекта?

Здравствуйте!
К сожалению, в ближайшее время репозиторий будет оставаться закрытым. 

Если у вас есть вопросы, можете писать мне на почту rulonchiks@yandex.ru
